name: NX_CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
  release:
    types: [published]


jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: master
        submodules: recursive
    - name: Build
      run: |
        git config --global --add safe.directory `pwd`;
        pacman -S devkitA64 libnx switch-tools switch-mesa switch-glad switch-glm
        cd Atmosphere
        make -j$(nproc) 
    # - name: Upload file
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: ${{ steps.repo.outputs._1 }} 
    #     path: 
    # - name: Upload binaries to release
    #   uses: svenstaro/upload-release-action@v2
    #   with:
    #     repo_token: ${{ secrets.release_token }}
    #     file: 
    #     tag: ${{ github.ref }}
    #     overwrite: true
    #     file_glob: true
