name: NX_CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
  release:
    types: [published]


jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: master
        submodules: recursive
    - name: Build
      run: |
        apt update 
        apt install -y python3-pip
        pip install lz4
        git config --global --add safe.directory `pwd`;
        git submodule update --init --recursive
        dkp-pacman -Syu --noconfirm
        dkp-pacman -Syu --noconfirm switch-dev deko3d devkita64-cmake switch-cmake switch-pkg-config devkitA64 devkitA64-gdb switch-tools general-tools uam devkitARM devkitARM-gdb devkitarm-rules switch-portlibs devkitARM
        git clone --depth 1 https://github.com/SciresM/hactool  --recursive && git config --global --add safe.directory hactool; cd hactool && cp config.mk.template config.mk && make && chmod +x hactool
        export PATH=$PATH:$(pwd)/hactool
        cd ../
        export DEVKITPRO=/opt/devkitpro
        cd troposphere/haze
        make -j4
        cd ../..
        make -f atmosphere.mk dist-no-debug -j4
        ls out
    - uses: actions/upload-artifact@v4
      with:
          name: release
          path: |
           ${{ github.workspace }}/out/nintendo_nx_arm64_armv8a
           ${{ github.workspace }}/out/*.zip
    # - name: Upload file
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: ${{ steps.repo.outputs._1 }} 
    #     path: 
    # - name: Upload binaries to release
    #   uses: svenstaro/upload-release-action@v2
    #   with:
    #     repo_token: ${{ secrets.release_token }}
    #     file: 
    #     tag: ${{ github.ref }}
    #     overwrite: true
    #     file_glob: true
