name: NX_CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
  release:
    types: [published]


jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: master
        submodules: recursive
    - name: Build
      run: |
        sudo -E apt update 
        sudo -E apt install -y python3-pip tree
        sudo -E pip install lz4
        sudo -E git config --global --add safe.directory `pwd`;
        sudo -E git submodule update --init --recursive
        sudo -E dkp-pacman -Syu --noconfirm
        sudo -E dkp-pacman -Syu --noconfirm switch-dev deko3d devkita64-cmake switch-cmake switch-pkg-config devkitA64 devkitA64-gdb switch-tools general-tools uam devkitARM devkitARM-gdb devkitarm-rules switch-portlibs devkitARM
        sudo -E git clone --depth 1 https://github.com/SciresM/hactool  --recursive && git config --global --add safe.directory hactool; cd hactool && cp config.mk.template config.mk && make && chmod +x hactool
        export PATH=$PATH:$(pwd)/hactool
        cd ../
        export DEVKITPRO=/opt/devkitpro
        cd troposphere/haze
        sudo -E make -j4
        cd ../..
        sudo -E make -j4
        mv out/nintendo_nx_arm64_armv8a/release/*/master-*-dirty.zip out/Atmosphere.zip
        tree out
    - uses: actions/upload-artifact@v4
      with:
          name: release
          path: out/Atmosphere.zip
          # /__w/Atmosphere/Atmosphere/out/nintendo_nx_arm64_armv8a/release/atmosphere-1.9.1-heads/master-0e438ca-dirty

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@master
      with:
        repo_token: ${{ secrets.repo_token }}
        file: out/Atmosphere.zip
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
